

export const privacyList = [
  {id: 0, title: 'Public', selected: false, key: 'public'},
  {id: 1, title: 'Private', selected: false, key: 'public'},
];
export const genderList = [
  {id: 0, title: 'Male', genderEmoji: '../../../emojis/Male.png', selected: false, key: 'gender'},
  {id: 1, title: ' Female', genderEmoji: '../../../emojis/Female.png', selected: false, key: 'gender'},
  {id: 2, title: ' Non-Binary', genderEmoji: '../../../emojis/Non-Binary.png', selected: false, key: 'gender'}
  //{id: 3, title: 'Other', emoji: selected: false, key: 'gender'},
];

export const accountTypeList = [
  {id: 0, title: 'Entrepreneur', selected: false, key: 'account_type', value: 'entrepreneur'},
  {id: 1, title: 'Job Seeker', selected: false, key: 'account_type', value: 'job_seeker'},
  {id: 2, title: 'Student', selected: false, key: 'account_type', value: 'student'},
  {id: 3, title: 'Recruiter', selected: false, key: 'account_type', value: 'recruiter'},
  {id: 4, title: 'Hiring Manager', selected: false, key: 'account_type', value: 'hiring_manager'},
  {id: 5, title: 'Professional', selected: false, key: 'account_type', value: 'professional'},
];

export const filterList = [
  {id: 0, title: 'Latest', selected: false, key: 'filter'},
  {id: 1, title: 'Oldest', selected: false, key: 'filter'},
  //{id: 2, title: '', selected: false, key: 'filter'}
];

export const degreeList = [
  {id: 0, title: 'AA', selected: false, key: 'degree'},
  {id: 1, title: 'AAS', selected: false, key: 'degree'},
  {id: 2, title: 'Certificate', selected: false, key: 'degree'},
  {id: 3, title: 'BS', selected: false, key: 'degree'},
  {id: 4, title: 'BA', selected: false, key: 'degree'},
  {id: 5, title: 'BFA', selected: false, key: 'degree'},
  {id: 6, title: 'MEd', selected: false, key: 'degree'},
  {id: 7, title: 'ME', selected: false, key: 'degree'},
  {id: 8, title: 'MS', selected: false, key: 'degree'},
  {id: 9, title: 'MA', selected: false, key: 'degree'},
  {id: 10, title: 'MFA', selected: false, key: 'degree'},
  {id: 11, title: 'MBA', selected: false, key: 'degree'},
  {id: 12, title: 'PhD', selected: false, key: 'degree'},
];

export const ethnicityList = [
  {id: 0, title: 'Asian', selected: false, key: 'ethnicity'},
  {id: 1, title: 'Black', selected: false, key: 'ethnicity'},
  {id: 2, title: 'Hispanic', selected: false, key: 'ethnicity'},
  {id: 3, title: 'Indian', selected: false, key: 'ethnicity'},
  {id: 4, title: 'Latin American', selected: false, key: 'ethnicity'},
  {id: 5, title: 'Mixed Race', selected: false, key: 'ethnicity'},
  {id: 6, title: 'Native American', selected: false, key: 'ethnicity'},
  {id: 7, title: 'Pacific Islander', selected: false, key: 'ethnicity'},
  {id: 8, title: 'South East Asian', selected: false, key: 'ethnicity'},
  {id: 9, title: 'White', selected: false, key: 'ethnicity'},
];

export const occupationList = [
{id: 0, title: 'Accountant', emoji: '💼', selected: false, key: 'occupation'},
{id: 1, title: 'Attorney', emoji: '⚖️' , selected: false, key: 'occupation'},
{id: 2, title: 'Business Analyst', emoji: '📊', selected: false, key: 'occupation'},
{id: 3, title: 'Business Development Manager', emoji: '👔', selected: false, key: 'occupation'},
{id: 4, title: 'Business Intelligence Analyst', emoji: '📊', selected: false, key: 'occupation'},
{id: 5, title: 'Business Intelligence Manager', emoji: '👔', selected: false, key: 'occupation'},
{id: 6, title: 'Chief Executive Officer', emoji: '👨🏽‍💼', selected: false, key: 'occupation'},
{id: 7, title: 'Chief Marketing Officer', emoji: '👩🏻‍💼', selected: false, key: 'occupation'},
{id: 8, title: 'Chief Operating Officer', emoji: '👨🏿‍💼', selected: false, key: 'occupation'},
{id: 9, title: 'Chief Technology Officer', emoji: '👨🏼‍💻', selected: false, key: 'occupation'},
{id: 10, title: 'Coach', emoji: '👟', selected: false, key: 'occupation'},
{id: 11, title: 'Consulant', emoji: '👩🏽‍💼', selected: false, key: 'occupation'},
{id: 12, title: 'Content Strategist', emoji: '🗂', selected: false, key: 'occupation'},
{id: 13, title: 'Customer Relationship Manager (CRM)', emoji: '👫', selected: false, key: 'occupation'},
{id: 14, title: 'Data Analyst', emoji: '📈', selected: false, key: 'occupation'},
{id: 15, title: 'Data Scientist', emoji: '👩‍🔬', selected: false, key: 'occupation'},
{id: 16, title: 'Data Visualization Specialist', emoji: '📊', selected: false, key: 'occupation'},
{id: 17, title: 'Database Administrator (DBA)', emoji: '📉', selected: false, key: 'occupation'},
{id: 18, title: 'Entrepreneur & Founder', emoji: '👨🏼‍💼', selected: false, key: 'occupation'},
{id: 19, title: 'Financial Analyst', emoji: '💵', selected: false, key: 'occupation'},
{id: 20, title: 'Fontend Engineer', emoji: '👨🏻‍💻', selected: false, key: 'occupation'},
{id: 21, title: 'Machine Learning Specialist', emoji: '💻', selected: false, key: 'occupation'},
{id: 22, title: 'Market Researcher', emoji: '🔍', selected: false, key: 'occupation'},
{id: 23, title: 'Marketing Analyst', emoji: '📊', selected: false, key: 'occupation'},
{id: 24, title: 'Marketing Manager', emoji: '👔', selected: false, key: 'occupation'},
{id: 25, title: 'Media Planning Specialist', emoji: '🎞', selected: false, key: 'occupation'},
{id: 26, title: 'Mobile Software Developer', emoji: '📱', selected: false, key: 'occupation'},
{id: 27, title: 'Online Marketing Specialist', emoji: '⌨️', selected: false, key: 'occupation'},
{id: 28, title: 'Paralegal', emoji: '👨🏻‍⚖️', selected: false, key: 'occupation'},
{id: 29, title: 'Partner', emoji: '👫', selected: false, key: 'occupation'},
{id: 30, title: 'Phd. Candidate', emoji: '👩🏽‍🎓', selected: false, key: 'occupation'},
{id: 31, title: 'Product Manager', emoji: '👨🏻‍💻', selected: false, key: 'occupation'},
{id: 32, title: 'Professor', emoji: '👩‍🏫', selected: false, key: 'occupation'},
{id: 33, title: 'Project Manager', emoji: '📋', selected: false, key: 'occupation'},
{id: 34, title: 'Public Relations', emoji: '👨‍👩‍👧‍👦', selected: false, key: 'occupation'},
{id: 35, title: 'Researcher', emoji: '🔍', selected: false, key: 'occupation'},
{id: 36, title: 'Senior Manager', emoji: '👔', selected: false, key: 'occupation'},
{id: 37, title: 'Software Engineer', emoji: '👨🏻‍💻', selected: false, key: 'occupation'},
{id: 38, title: 'Strategic Planning Manager', emoji: '👨🏻‍💻', selected: false, key: 'occupation'},
{id: 39, title: 'Teacher', emoji: '📖', selected: false, key: 'occupation'},
{id: 40, title: 'Tech support', emoji: '💻', selected: false, key: 'occupation'},
{id: 41, title: 'UI/UX Designer', emoji: '👩🏻‍💻', selected: false, key: 'occupation'},
{id: 42, title: 'User Researcher', emoji: '🔍', selected: false, key: 'occupation'},
{id: 43, title: 'Vice President', emoji: '👨🏻‍💼', selected: false, key: 'occupation'},
{id: 44, title: 'Web Architecture and Framework Development', emoji: '🖥', selected: false, key: 'occupation'},
{id: 45, title: 'Writer', emoji: '🖋', selected: false, key: 'occupation'}
];

export const occupationArray = [
'💼 Accountant',
'⚖️ Attorney',
'📊 Business Analyst',
'👔 Business Development Manager',
'📊 Business Intelligence Analyst',
'👔 Business Intelligence Manager',
'👨🏽‍💼 Chief Executive Officer',
'👩🏻‍💼 Chief Marketing Officer',
'👨🏿‍💼 Chief Operating Officer',
'👨🏼‍💻 Chief Technology Officer',
'👟 Coach',
'👩🏽‍💼 Consulant',
'🗂 Content Strategist',
'👫 Customer Relationship Manager (CRM)',
'📈 Data Analyst',
'👩‍🔬 Data Scientist',
'📊 Data Visualization Specialist',
'📉 Database Administrator (DBA)',
'👨🏼‍💼 Entrepreneur & Founder',
'💵 Financial Analyst',
'👨🏻‍💻 Frontend Engineer',
'💻 Machine Learning Specialist',
'🔍 Market Researcher',
'📊 Marketing Analyst',
'👔 Marketing Manager',
'🎞 Media Planning Specialist',
'📱 Mobile Software Developer',
'⌨️ Online Marketing Specialist',
'👨🏻‍⚖️ Paralegal',
'👫 Partner',
'👩🏽‍🎓 Phd. Candidate',
'👨🏻‍💻 Product Manager',
'👩‍🏫 Professor',
'📋 Project Manager',
'👨‍👩‍👧‍👦 Public Relations',
'🔍 Researcher',
'👔 Senior Manager',
'👨🏻‍💻 Software Engineer',
'👨🏻‍💻 Strategic Planning Manager',
'📖 Teacher',
'💻 Tech Support',
'👩🏻‍💻 UI/UX Designer',
'🔍 User Researcher',
'👨🏻‍💼 Vice President',
'🖥 Web Architecture and Framework Development',
'🖋 Writer',
];
export const ageRangeList = [
  {id: 0, title: '13-17', selected: false, key: 'age_range'},
  {id: 1, title: '18-24', selected: false, key: 'age_range'},
  {id: 2, title: '25-34', selected: false, key: 'age_range'},
  {id: 3, title: '35-44', selected: false, key: 'age_range'},
  {id: 4, title: '45-54', selected: false, key: 'age_range'},
  {id: 5, title: '55-64', selected: false, key: 'age_range'},
  {id: 6, title: '65+', selected: false, key: 'age_range'},
];
export const requiredExperienceList = [
  {id: 1, title: '0-2 Years', selected: false, key: 'required_experience'},
  {id: 2, title: '3-5 Years', selected: false, key: 'required_experience'},
  {id: 3, title: '6-10 Years', selected: false, key: 'required_experience'},
  {id: 4, title: '10+ Years', selected: false, key: 'required_experience'},
];
export const userTypesList = [
  { title: 'Job Seeker', selected: false, id: 'job_seeker', key: 'user_type'},
  { title: 'Student', selected: false, id: 'student', key: 'user_type'},
  { title: 'Professional', selected: false, id: 'professional', key: 'user_type'},
  { title: 'Hiring Manager', selected: false, id: 'hiring_manager', key: 'user_type'},
  { title: 'Recruiter', selected: false, id: 'recruiter', key: 'user_type'},
];

export const dateOfBirthMonth = [
  {id: '01', title: 'Janurary', selected: false, key: 'month'},
  {id: '02', title: 'February', selected: false, key: 'month'},
  {id: '03', title: 'March', selected: false, key: 'month'},
  {id: '04', title: 'April', selected: false, key: 'month'},
  {id: '05', title: 'May', selected: false, key: 'month'},
  {id: '06', title: 'June', selected: false, key: 'month'},
  {id: '07', title: 'July', selected: false, key: 'month'},
  {id: '08', title: 'August', selected: false, key: 'month'},
  {id: '09', title: 'September', selected: false, key: 'month'},
  {id: '10', title: 'October', selected: false, key: 'month'},
  {id: '11', title: 'November', selected: false, key: 'month'},
  {id: '12', title: 'December', selected: false, key: 'month'},
];

export const dateOfBirthDay = [
  {id: 1, title: '01', selected: false, key: 'day'},
  {id: 2, title: '02', selected: false, key: 'day'},
  {id: 3, title: '03', selected: false, key: 'day'},
  {id: 4, title: '04', selected: false, key: 'day'},
  {id: 5, title: '05', selected: false, key: 'day'},
  {id: 6, title: '06', selected: false, key: 'day'},
  {id: 7, title: '07', selected: false, key: 'day'},
  {id: 8, title: '08', selected: false, key: 'day'},
  {id: 9, title: '09', selected: false, key: 'day'},
  {id: 10, title: '10', selected: false, key: 'day'},
  {id: 11, title: '11', selected: false, key: 'day'},
  {id: 12, title: '12', selected: false, key: 'day'},
  {id: 13, title: '13', selected: false, key: 'day'},
  {id: 14, title: '14', selected: false, key: 'day'},
  {id: 15, title: '15', selected: false, key: 'day'},
  {id: 16, title: '16', selected: false, key: 'day'},
  {id: 17, title: '17', selected: false, key: 'day'},
  {id: 18, title: '18', selected: false, key: 'day'},
  {id: 19, title: '19', selected: false, key: 'day'},
  {id: 20, title: '20', selected: false, key: 'day'},
  {id: 21, title: '21', selected: false, key: 'day'},
  {id: 22, title: '22', selected: false, key: 'day'},
  {id: 23, title: '23', selected: false, key: 'day'},
  {id: 24, title: '24', selected: false, key: 'day'},
  {id: 25, title: '25', selected: false, key: 'day'},
  {id: 26, title: '26', selected: false, key: 'day'},
  {id: 27, title: '27', selected: false, key: 'day'},
  {id: 28, title: '28', selected: false, key: 'day'},
  {id: 29, title: '29', selected: false, key: 'day'},
  {id: 30, title: '30', selected: false, key: 'day'},
  {id: 31, title: '31', selected: false, key: 'day'},
];

export const dateOfBirthYear = [
  {id: 0, title: '1901', selected: false, key: 'year'},
  {id: 1, title: '1902', selected: false, key: 'year'},
  {id: 2, title: '1903', selected: false, key: 'year'},
  {id: 3, title: '1904', selected: false, key: 'year'},
  {id: 4, title: '1905', selected: false, key: 'year'},
  {id: 5, title: '1906', selected: false, key: 'year'},
  {id: 6, title: '1907', selected: false, key: 'year'},
  {id: 7, title: '1908', selected: false, key: 'year'},
  {id: 8, title: '1909', selected: false, key: 'year'},
  {id: 9, title: '1910', selected: false, key: 'year'},
  {id: 10, title: '1911', selected: false, key: 'year'},
  {id: 11, title: '1912', selected: false, key: 'year'},
  {id: 12, title: '1913', selected: false, key: 'year'},
  {id: 13, title: '1914', selected: false, key: 'year'},
  {id: 14, title: '1915', selected: false, key: 'year'},
  {id: 15, title: '1916', selected: false, key: 'year'},
  {id: 16, title: '1917', selected: false, key: 'year'},
  {id: 17, title: '1918', selected: false, key: 'year'},
  {id: 18, title: '1919', selected: false, key: 'year'},
  {id: 19, title: '1920', selected: false, key: 'year'},
  {id: 20, title: '1921', selected: false, key: 'year'},
  {id: 21, title: '1922', selected: false, key: 'year'},
  {id: 22, title: '1923', selected: false, key: 'year'},
  {id: 23, title: '1924', selected: false, key: 'year'},
  {id: 24, title: '1925', selected: false, key: 'year'},
  {id: 25, title: '1926', selected: false, key: 'year'},
  {id: 26, title: '1927', selected: false, key: 'year'},
  {id: 27, title: '1928', selected: false, key: 'year'},
  {id: 28, title: '1929', selected: false, key: 'year'},
  {id: 29, title: '1930', selected: false, key: 'year'},
  {id: 30, title: '1931', selected: false, key: 'year'},
  {id: 31, title: '1932', selected: false, key: 'year'},
  {id: 32, title: '1933', selected: false, key: 'year'},
  {id: 33, title: '1934', selected: false, key: 'year'},
  {id: 34, title: '1935', selected: false, key: 'year'},
  {id: 35, title: '1936', selected: false, key: 'year'},
  {id: 36, title: '1937', selected: false, key: 'year'},
  {id: 37, title: '1938', selected: false, key: 'year'},
  {id: 38, title: '1939', selected: false, key: 'year'},
  {id: 39, title: '1940', selected: false, key: 'year'},
  {id: 40, title: '1941', selected: false, key: 'year'},
  {id: 41, title: '1942', selected: false, key: 'year'},
  {id: 42, title: '1943', selected: false, key: 'year'},
  {id: 43, title: '1944', selected: false, key: 'year'},
  {id: 44, title: '1945', selected: false, key: 'year'},
  {id: 45, title: '1946', selected: false, key: 'year'},
  {id: 46, title: '1947', selected: false, key: 'year'},
  {id: 47, title: '1948', selected: false, key: 'year'},
  {id: 48, title: '1949', selected: false, key: 'year'},
  {id: 49, title: '1950', selected: false, key: 'year'},
  {id: 50, title: '1951', selected: false, key: 'year'},
  {id: 51, title: '1952', selected: false, key: 'year'},
  {id: 52, title: '1953', selected: false, key: 'year'},
  {id: 53, title: '1954', selected: false, key: 'year'},
  {id: 54, title: '1955', selected: false, key: 'year'},
  {id: 55, title: '1956', selected: false, key: 'year'},
  {id: 56, title: '1957', selected: false, key: 'year'},
  {id: 57, title: '1958', selected: false, key: 'year'},
  {id: 58, title: '1959', selected: false, key: 'year'},
  {id: 59, title: '1960', selected: false, key: 'year'},
  {id: 60, title: '1961', selected: false, key: 'year'},
  {id: 61, title: '1962', selected: false, key: 'year'},
  {id: 62, title: '1963', selected: false, key: 'year'},
  {id: 63, title: '1964', selected: false, key: 'year'},
  {id: 64, title: '1965', selected: false, key: 'year'},
  {id: 65, title: '1966', selected: false, key: 'year'},
  {id: 66, title: '1967', selected: false, key: 'year'},
  {id: 67, title: '1968', selected: false, key: 'year'},
  {id: 68, title: '1969', selected: false, key: 'year'},
  {id: 69, title: '1970', selected: false, key: 'year'},
  {id: 70, title: '1971', selected: false, key: 'year'},
  {id: 71, title: '1972', selected: false, key: 'year'},
  {id: 72, title: '1973', selected: false, key: 'year'},
  {id: 73, title: '1974', selected: false, key: 'year'},
  {id: 74, title: '1975', selected: false, key: 'year'},
  {id: 75, title: '1976', selected: false, key: 'year'},
  {id: 76, title: '1977', selected: false, key: 'year'},
  {id: 77, title: '1978', selected: false, key: 'year'},
  {id: 78, title: '1979', selected: false, key: 'year'},
  {id: 79, title: '1980', selected: false, key: 'year'},
  {id: 80, title: '1981', selected: false, key: 'year'},
  {id: 81, title: '1982', selected: false, key: 'year'},
  {id: 82, title: '1983', selected: false, key: 'year'},
  {id: 83, title: '1984', selected: false, key: 'year'},
  {id: 84, title: '1985', selected: false, key: 'year'},
  {id: 85, title: '1986', selected: false, key: 'year'},
  {id: 86, title: '1987', selected: false, key: 'year'},
  {id: 87, title: '1988', selected: false, key: 'year'},
  {id: 88, title: '1989', selected: false, key: 'year'},
  {id: 89, title: '1990', selected: false, key: 'year'},
  {id: 90, title: '1991', selected: false, key: 'year'},
  {id: 91, title: '1992', selected: false, key: 'year'},
  {id: 92, title: '1993', selected: false, key: 'year'},
  {id: 93, title: '1994', selected: false, key: 'year'},
  {id: 94, title: '1995', selected: false, key: 'year'},
  {id: 95, title: '1996', selected: false, key: 'year'},
  {id: 96, title: '1997', selected: false, key: 'year'},
  {id: 97, title: '1998', selected: false, key: 'year'},
  {id: 98, title: '1999', selected: false, key: 'year'},
  {id: 99, title: '2000', selected: false, key: 'year'},
  {id: 100, title: '2001', selected: false, key: 'year'},
  {id: 101, title: '2002', selected: false, key: 'year'},
  {id: 102, title: '2003', selected: false, key: 'year'},
  {id: 103, title: '2004', selected: false, key: 'year'},
  {id: 104, title: '2005', selected: false, key: 'year'},
  {id: 105, title: '2006', selected: false, key: 'year'},
  {id: 106, title: '2007', selected: false, key: 'year'},
  {id: 107, title: '2008', selected: false, key: 'year'},
  {id: 108, title: '2009', selected: false, key: 'year'},
  {id: 109, title: '2010', selected: false, key: 'year'},
  {id: 110, title: '2011', selected: false, key: 'year'},
  {id: 111, title: '2012', selected: false, key: 'year'},
  {id: 112, title: '2013', selected: false, key: 'year'},
  {id: 113, title: '2014', selected: false, key: 'year'},
  {id: 114, title: '2015', selected: false, key: 'year'},
  {id: 115, title: '2016', selected: false, key: 'year'},
  {id: 116, title: '2017', selected: false, key: 'year'},
  {id: 117, title: '2018', selected: false, key: 'year'},
];

export const educationExpectedYear = [
{id: 124, title: "2025", selected: false, key: "year"},
{id: 123, title: "2024", selected: false, key: "year"},
{id: 122, title: "2023", selected: false, key: "year"},
{id: 121, title: "2022", selected: false, key: "year"},
{id: 120, title: "2021", selected: false, key: "year"},
{id: 119, title: "2020", selected: false, key: "year"},
{id: 118, title: "2019", selected: false, key: "year"},
{id: 117, title: "2018", selected: false, key: "year"},
{id: 116, title: "2017", selected: false, key: "year"},
{id: 115, title: "2016", selected: false, key: "year"},
{id: 114, title: "2015", selected: false, key: "year"},
{id: 113, title: "2014", selected: false, key: "year"},
{id: 112, title: "2013", selected: false, key: "year"},
{id: 111, title: "2012", selected: false, key: "year"},
{id: 110, title: "2011", selected: false, key: "year"},
{id: 109, title: "2010", selected: false, key: "year"},
{id: 108, title: "2009", selected: false, key: "year"},
{id: 107, title: "2008", selected: false, key: "year"},
{id: 106, title: "2007", selected: false, key: "year"},
{id: 105, title: "2006", selected: false, key: "year"},
{id: 104, title: "2005", selected: false, key: "year"},
{id: 103, title: "2004", selected: false, key: "year"},
{id: 102, title: "2003", selected: false, key: "year"},
{id: 101, title: "2002", selected: false, key: "year"},
{id: 100, title: "2001", selected: false, key: "year"},
{id: 99, title: "2000", selected: false, key: "year"},
{id: 98, title: "1999", selected: false, key: "year"},
{id: 97, title: "1998", selected: false, key: "year"},
{id: 96, title: "1997", selected: false, key: "year"},
{id: 95, title: "1996", selected: false, key: "year"},
{id: 94, title: "1995", selected: false, key: "year"},
{id: 93, title: "1994", selected: false, key: "year"},
{id: 92, title: "1993", selected: false, key: "year"},
{id: 91, title: "1992", selected: false, key: "year"},
{id: 90, title: "1991", selected: false, key: "year"},
{id: 89, title: "1990", selected: false, key: "year"},
{id: 88, title: "1989", selected: false, key: "year"},
{id: 87, title: "1988", selected: false, key: "year"},
{id: 86, title: "1987", selected: false, key: "year"},
{id: 85, title: "1986", selected: false, key: "year"},
{id: 84, title: "1985", selected: false, key: "year"},
{id: 83, title: "1984", selected: false, key: "year"},
{id: 82, title: "1983", selected: false, key: "year"},
{id: 81, title: "1982", selected: false, key: "year"},
{id: 80, title: "1981", selected: false, key: "year"},
{id: 79, title: "1980", selected: false, key: "year"},
{id: 78, title: "1979", selected: false, key: "year"},
{id: 77, title: "1978", selected: false, key: "year"},
{id: 76, title: "1977", selected: false, key: "year"},
{id: 75, title: "1976", selected: false, key: "year"},
{id: 74, title: "1975", selected: false, key: "year"},
{id: 73, title: "1974", selected: false, key: "year"},
{id: 72, title: "1973", selected: false, key: "year"},
{id: 71, title: "1972", selected: false, key: "year"},
{id: 70, title: "1971", selected: false, key: "year"},
{id: 69, title: "1970", selected: false, key: "year"},
{id: 68, title: "1969", selected: false, key: "year"},
{id: 67, title: "1968", selected: false, key: "year"},
{id: 66, title: "1967", selected: false, key: "year"},
{id: 65, title: "1966", selected: false, key: "year"},
{id: 64, title: "1965", selected: false, key: "year"},
{id: 63, title: "1964", selected: false, key: "year"},
{id: 62, title: "1963", selected: false, key: "year"},
{id: 61, title: "1962", selected: false, key: "year"},
{id: 60, title: "1961", selected: false, key: "year"},
{id: 59, title: "1960", selected: false, key: "year"},
{id: 58, title: "1959", selected: false, key: "year"},
{id: 57, title: "1958", selected: false, key: "year"},
{id: 56, title: "1957", selected: false, key: "year"},
{id: 55, title: "1956", selected: false, key: "year"},
{id: 54, title: "1955", selected: false, key: "year"},
{id: 53, title: "1954", selected: false, key: "year"},
{id: 52, title: "1953", selected: false, key: "year"},
{id: 51, title: "1952", selected: false, key: "year"},
{id: 50, title: "1951", selected: false, key: "year"}
];

export const workYear = [
{id: 118, title: "2019", selected: false, key: "year"},
{id: 117, title: "2018", selected: false, key: "year"},
{id: 116, title: "2017", selected: false, key: "year"},
{id: 115, title: "2016", selected: false, key: "year"},
{id: 114, title: "2015", selected: false, key: "year"},
{id: 113, title: "2014", selected: false, key: "year"},
{id: 112, title: "2013", selected: false, key: "year"},
{id: 111, title: "2012", selected: false, key: "year"},
{id: 110, title: "2011", selected: false, key: "year"},
{id: 109, title: "2010", selected: false, key: "year"},
{id: 108, title: "2009", selected: false, key: "year"},
{id: 107, title: "2008", selected: false, key: "year"},
{id: 106, title: "2007", selected: false, key: "year"},
{id: 105, title: "2006", selected: false, key: "year"},
{id: 104, title: "2005", selected: false, key: "year"},
{id: 103, title: "2004", selected: false, key: "year"},
{id: 102, title: "2003", selected: false, key: "year"},
{id: 101, title: "2002", selected: false, key: "year"},
{id: 100, title: "2001", selected: false, key: "year"},
{id: 99, title: "2000", selected: false, key: "year"},
{id: 98, title: "1999", selected: false, key: "year"},
{id: 97, title: "1998", selected: false, key: "year"},
{id: 96, title: "1997", selected: false, key: "year"},
{id: 95, title: "1996", selected: false, key: "year"},
{id: 94, title: "1995", selected: false, key: "year"},
{id: 93, title: "1994", selected: false, key: "year"},
{id: 92, title: "1993", selected: false, key: "year"},
{id: 91, title: "1992", selected: false, key: "year"},
{id: 90, title: "1991", selected: false, key: "year"},
{id: 89, title: "1990", selected: false, key: "year"},
{id: 88, title: "1989", selected: false, key: "year"},
{id: 87, title: "1988", selected: false, key: "year"},
{id: 86, title: "1987", selected: false, key: "year"},
{id: 85, title: "1986", selected: false, key: "year"},
{id: 84, title: "1985", selected: false, key: "year"},
{id: 83, title: "1984", selected: false, key: "year"},
{id: 82, title: "1983", selected: false, key: "year"},
{id: 81, title: "1982", selected: false, key: "year"},
{id: 80, title: "1981", selected: false, key: "year"},
{id: 79, title: "1980", selected: false, key: "year"},
{id: 78, title: "1979", selected: false, key: "year"},
{id: 77, title: "1978", selected: false, key: "year"},
{id: 76, title: "1977", selected: false, key: "year"},
{id: 75, title: "1976", selected: false, key: "year"},
{id: 74, title: "1975", selected: false, key: "year"},
{id: 73, title: "1974", selected: false, key: "year"},
{id: 72, title: "1973", selected: false, key: "year"},
{id: 71, title: "1972", selected: false, key: "year"},
{id: 70, title: "1971", selected: false, key: "year"},
{id: 69, title: "1970", selected: false, key: "year"},
{id: 68, title: "1969", selected: false, key: "year"},
{id: 67, title: "1968", selected: false, key: "year"},
{id: 66, title: "1967", selected: false, key: "year"},
{id: 65, title: "1966", selected: false, key: "year"},
{id: 64, title: "1965", selected: false, key: "year"},
{id: 63, title: "1964", selected: false, key: "year"},
{id: 62, title: "1963", selected: false, key: "year"},
{id: 61, title: "1962", selected: false, key: "year"},
{id: 60, title: "1961", selected: false, key: "year"},
{id: 59, title: "1960", selected: false, key: "year"},
{id: 58, title: "1959", selected: false, key: "year"},
{id: 57, title: "1958", selected: false, key: "year"},
{id: 56, title: "1957", selected: false, key: "year"},
{id: 55, title: "1956", selected: false, key: "year"},
{id: 54, title: "1955", selected: false, key: "year"},
{id: 53, title: "1954", selected: false, key: "year"},
{id: 52, title: "1953", selected: false, key: "year"},
{id: 51, title: "1952", selected: false, key: "year"},
{id: 50, title: "1951", selected: false, key: "year"}
];



export const jobSkillsArray = ["Accounting", "Administrative", "Adobe Photoshop", "Android", "Business analysis", "Business development", "Business intelligence", "Business management", "Business storytelling", "C", "C#", "C++", "Channel marketing", "Coaching", "Consulting", "Content management", "Content marketing", "Content strategy", "Critical thinking", "Data Vizualization", "Data analysis", "Data presentation", "Database administration", "Delegating tasks", "Digital media", "Economics", "Editing", "Financial Modeling", "Git", "HTML", "Ionic", "Java", "JavaScript", "Kotlin", "Leadership", "Linux", "Market Research", "Market research", "Media planning", "Microsoft Excel", "Microsoft Office Suite", "Microsoft Power Point", "Microsoft Word", "Middleware and integration software", "Mobile development", "MySQL", "Negotiation", "Network and information security", "Newsletters", "Node.js", "Nonverbal communication", "Online marketing", "PHP", "Presentation", "Problem-solving", "Project management", "Public relations", "Python", "R", "React", "React Native", "Relationship management", "Research", "Ruby On Rails", "SQL", "Scrum", "Social media", "Software engineering", "Software management", "Storage systems and management", "Strategic planning", "Tableau", "Tech support", "UI/UX", "Unity", "User Research", "User interface design", "Web architecture and development framework", "Writing", "iOS", "jQuery"];